projects:
  webLancerBackend:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        graphQLApiId: d6pdlbyvbffjtd4yqxcvjpm6uq
      endpoints:
        prod: >-
          https://jss3bovswra5nbnygu3afhepte.appsync-api.us-east-2.amazonaws.com/graphql
